config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  category_slug_pattern = /[a-z]+[-_0-9a-z]*[0-9a-z]/
  post_slug_pattern = /[a-z0-9]+[-_.a-z0-9]*[a-z0-9]+/
  archive_constraints = { year: /19\d\d|2[01]\d\d/, month: /0[1-9]|1[0-2]/, day: /0[1-9]|[12]\d|3[01]/ }

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :lock do
    member do
      put :lock, defaults: { format: :json }
      delete :lock, action: :unlock, defaults: { format: :json }
    end
  end

  resources :post_categories, :posts, :post_tags, :post_images, only: %i[update destroy]
  resources :post_links, only: :destroy
  resources :editorial_members, only: %i[update destroy]
  resources :featured_posts, only: :destroy
  resources :post_illustrations, only: :create
  resources :post_groups, only: %i[update destroy]
  resources :post_attachments, only: :destroy

  scope '/(:locale)', constraints: { locale: /ru|en|sv|cn/ } do
    resources :post_categories, except: %i[index show update destroy]
    resources :posts, except: %i[new update destroy] do
      collection do
        get 'search'
        get 'categories/:category_slug' => :category, as: :posts_category, constraints: { category_slug: category_slug_pattern }
        get 'tagged/(:tag_name)' => :tagged, as: :tagged, constraints: { tag_name: /[^\/]+?/ }
        get 'archive/(:year)(-:month)(-:day)' => :archive, as: :archive, constraints: archive_constraints
        get 'rss/zen.xml' => :zen, defaults: { format: :xml }
        get 'rss.xml' => :rss, as: :rss, defaults: { format: :xml }
        get ':category_slug' => :category, as: :short_category, constraints: { category_slug: category_slug_pattern }
        get ':id-:slug' => :show, constraints: { id: /\d+/, slug: post_slug_pattern }
      end
    end
    resources :post_tags, only: :edit
    resources :post_images, only: %i[edit create]
    resources :post_links, only: :create
    resources :editorial_members, only: %i[new create edit]
    resources :featured_posts, only: :create
    resources :post_groups, only: %i[show new create edit], concerns: :check

    scope :articles, controller: :articles do
      get '/' => :index, as: :articles
      get 'new' => :new, as: :new_article
      get 'archive/(:year)(-:month)(-:day)' => :archive, as: :articles_archive, constraints: archive_constraints
      get 'tagged/(:tag_name)' => :tagged, as: :tagged_articles, constraints: { tag_name: /[^\/]+?/ }
      get '/:category_slug' => :category, as: :articles_category, constraints: { category_slug: category_slug_pattern }
      get '/:post_id-:post_slug' => :show, as: :show_article, constraints: { post_id: /\d+/, post_slug: post_slug_pattern }
    end

    scope :news, controller: :news do
      get '/' => :index, as: :news_index
      get 'new' => :new, as: :new_news
      get 'archive/(:year)(-:month)(-:day)' => :archive, as: :news_archive, constraints: archive_constraints
      get 'tagged/(:tag_name)' => :tagged, as: :tagged_news, constraints: { tag_name: /[^\/]+?/ }
      get '/:category_slug' => :category, as: :news_category, constraints: { category_slug: category_slug_pattern }
      get '/:post_id-:post_slug' => :show, as: :show_news, constraints: { post_id: /\d+/, post_slug: post_slug_pattern }
    end

    scope :blog_posts, controller: :blog_posts do
      get '/' => :index, as: :blog_posts
      get 'new' => :new, as: :new_blog_post
      get 'archive/(:year)(-:month)(-:day)' => :archive, as: :blog_posts_archive, constraints: archive_constraints
      get 'tagged/(:tag_name)' => :tagged, as: :tagged_blog_posts, constraints: { tag_name: /[^\/]+?/ }
      get '/:category_slug' => :category, as: :blog_posts_category, constraints: { category_slug: category_slug_pattern }
      get '/:post_id-:post_slug' => :show, as: :show_blog_post, constraints: { post_id: /\d+/, post_slug: post_slug_pattern }
    end

    scope :authors, controller: 'authors' do
      get '/' => :index, as: :authors
      get ':slug' => :show, as: :author
    end

    scope 'u/:slug', controller: :profiles, constraints: { slug: %r{[^/]+} } do
      get 'posts' => :posts, as: :user_posts
    end

    namespace :admin do
      resources :post_types, only: %i[index show] do
        member do
          get :post_categories
          get :new_post
          get :post_tags
          get :authors
          put 'users/:user_id' => :add_user, as: :user
          delete 'users/:user_id' => :remove_user
        end
      end

      resources :post_categories, only: :show, concerns: %i[toggle priority] do
        member do
          put 'users/:user_id' => :add_user, as: :user
          delete 'users/:user_id' => :remove_user
        end
      end

      resources :posts, only: %i[index show], concerns: %i[lock toggle] do
        get 'search', on: :collection
        get 'images', on: :member
      end

      resources :post_tags, only: %i[index show] do
        get 'posts', on: :member
      end

      resources :post_illustrations, only: %i[index show]
      resources :post_images, only: %i[index show], concerns: %i[toggle priority]

      resources :post_groups, only: %i[index show], concerns: %i[toggle priority] do
        member do
          put 'categories/:category_id' => :add_category, as: :category
          delete 'categories/:category_id' => :remove_category
          put 'tags/:tag_id' => :add_tag, as: :tag
          delete 'tags/:tag_id' => :remove_tag
          get :tags, defaults: { format: :json }
        end
      end
      scope 'post_group_categories/:id', controller: :post_group_categories do
        post 'priority' => :priority, as: :priority_post_group_category, defaults: { format: :json }
      end
      scope 'post_group_tags/:id', controller: :post_group_tags do
        post 'priority' => :priority, as: :priority_post_group_tag, defaults: { format: :json }
      end

      resources :editorial_members, only: %i[index show], concerns: %i[toggle priority] do
        member do
          put 'post_types/:post_type_id' => :add_post_type, as: :post_type
          delete 'post_types/:post_type_id' => :remove_post_type
        end
      end

      resources :featured_posts, only: :index, concerns: :priority

      scope 'post_links', controller: :post_links do
        post ':id/priority' => :priority, as: :priority_post_link, defaults: { format: :json }
      end
    end

    namespace :my do
      get 'articles' => 'posts#articles'
      get 'news' => 'posts#news_index'
      get 'blog' => 'posts#blog_posts'
      get 'articles/new' => 'posts#new_article', as: :new_article
      get 'news/new' => 'posts#new_news', as: :new_news
      get 'blog_posts/new' => 'posts#new_blog_post', as: :new_blog_post

      resources :posts, except: :new
    end
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  include HasUuid
  include Toggleable

  DESCRIPTION_LIMIT = 5000
  META_LIMIT        = 255
  PRIORITY_RANGE    = (1..32767)

  toggleable :visible

  mount_uploader :image, PostImageUploader

  belongs_to :post

  after_initialize :set_next_priority
  before_validation :normalize_priority

  validates_presence_of :image
  validates_length_of :image_alt_text, maximum: META_LIMIT
  validates_length_of :caption, maximum: META_LIMIT
  validates_length_of :source_name, maximum: META_LIMIT
  validates_length_of :source_link, maximum: META_LIMIT
  validates_length_of :description, maximum: DESCRIPTION_LIMIT

  scope :recent, -> { order('id desc') }
  scope :ordered_by_priority, -> { order('priority asc, id asc') }
  scope :visible, -> { where(visible: true) }
  scope :list_for_visitors, -> { visible.ordered_by_priority }
  scope :list_for_administration, -> { ordered_by_priority }
  scope :siblings, -> (post_id) { where(post_id: post_id) }

  # @param [Integer] page
  def self.page_for_administration(page = 1)
    recent.page(page)
  end

  def self.entity_parameters
    %i[caption description image image_alt_text source_link source_name visible]
  end

  def self.creation_parameters
    entity_parameters + %i(post_id)
  end

  def name
    caption.blank? ? "#{post.title} — #{priority}" : caption
  end

  # @param [User] user
  def owned_by?(user)
    post.owned_by?(user)
  end

  # @param [User] user
  # @deprecated use component handler
  def editable_by?(user)
    Biovision::Components::BaseComponent.handler('posts', user).editable?(post)
  end

  def has_image_data?
    !caption.blank? || !source_name.blank? || !source_link.blank?
  end

  # @param [Integer] delta
  def change_priority(delta)
    new_priority = priority + delta
    criteria     = { priority: new_priority }
    adjacent     = self.class.siblings(post_id).find_by(criteria)
    if adjacent.is_a?(self.class) && (adjacent.id != id)
      adjacent.update!(priority: priority)
    end
    self.update(priority: new_priority)

    self.class.siblings(post_id).map { |e| [e.id, e.priority] }.to_h
  end

  private

  def set_next_priority
    if id.nil? && priority == 1
      self.priority = self.class.siblings(post_id).maximum(:priority).to_i + 1
    end
  end

  def normalize_priority
    self.priority = PRIORITY_RANGE.first if priority < PRIORITY_RANGE.first
    self.priority = PRIORITY_RANGE.last if priority > PRIORITY_RANGE.last
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < AdminController
  include ToggleableEntity
  include EntityPriority

  before_action :set_entity, except: [:index]

  # get /admin/post_images
  def index
    @collection = PostImage.page_for_administration(current_page)
  end

  # get /admin/post_images/:id
  def show
  end

  # get /admin/post_images/:id/posts
  def posts
    @collection = @entity.posts.page_for_administration(current_page)
  end

  private

  def component_class
    Biovision::Components::PostsComponent
  end

  def set_entity
    @entity = PostImage.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find post_image')
    end
  end
end

app/controllers/post_images_controller.rb
# frozen_string_literal: true

# Managing post images
class PostImagesController < AdminController
  before_action :set_entity, only: [:edit, :update, :destroy]
  before_action :restrict_editing, only: [:edit, :update, :destroy]

  # post /post_images
  def create
    @entity = PostImage.new(creation_parameters)
    if @entity.save
      form_processed_ok(images_admin_post_path(id: @entity.post_id))
    else
      form_processed_with_error(:new)
    end
  end

  # get /post_images/:id/edit
  def edit
  end

  # patch /post_images/:id
  def update
    if @entity.update(entity_parameters)
      form_processed_ok(admin_post_image_path(id: @entity.id))
    else
      form_processed_with_error(:edit)
    end
  end

  # delete /post_images/:id
  def destroy
    if @entity.destroy
      flash[:notice] = t('post_images.destroy.success')
    end
    redirect_to admin_post_path(id: @entity.post_id)
  end

  private

  def component_class
    Biovision::Components::PostsComponent
  end

  def set_entity
    @entity = PostImage.find_by(id: params[:id])
    handle_http_404('Cannot find post_image') if @entity.nil?
  end

  def restrict_editing
    unless component_handler.editable?(@entity.post)
      handle_http_401('Post image is not editable by current user')
    end
  end

  def entity_parameters
    params.require(:post_image).permit(PostImage.entity_parameters)
  end

  def creation_parameters
    params.require(:post_image).permit(PostImage.creation_parameters)
  end
end

app/views/post_images/_form.html.erb
<% model_name = entity.class.to_s.underscore %>
<%= form_with model: entity, html: { id: "#{model_name}-form" } do |f| %>
  <%= render partial: 'shared/list_of_errors', locals: { entity: entity } %>

  <dl>
    <dt><%= f.label :priority %></dt>
    <dd>
      <%=
        f.number_field(
            :priority,
            id:       "#{model_name}_priority",
            in:       PostImage::PRIORITY_RANGE,
            required: true
        )
      %>
    </dd>

    <dt><%= f.label :image %></dt>
    <dd>
      <% figure_id = "#{model_name}-image" %>
      <figure role="group" class="preview" id="<%= figure_id %>">
        <% if entity.image.blank? %>
          <%= f.label :image, image_tag('biovision/base/placeholders/image.svg') %>
        <% else %>
          <%= f.label :image, image_tag(entity.image.big.url) %>
        <% end %>
        <figcaption>
          <%=
            f.file_field(
                :image,
                id:     "#{model_name}_image",
                accept: 'image/jpeg,image/png',
                data:   { image: figure_id }
            )
          %>
        </figcaption>
      </figure>
      <div class="guideline"><%= t('.guidelines.image') %></div>
    </dd>

    <dt><%= f.label :image_alt_text %></dt>
    <dd>
      <%=
        f.text_field(
            :image_alt_text,
            id:        "#{model_name}_image_alt_text",
            size:      nil,
            maxlength: PostImage::META_LIMIT
        )
      %>
      <div class="guideline"><%= t('.guidelines.image_alt_text') %></div>
    </dd>

    <dt><%= f.label :caption %></dt>
    <dd>
      <%=
        f.text_field(
            :caption,
            id:        "#{model_name}_caption",
            size:      nil,
            maxlength: PostImage::META_LIMIT
        )
      %>
      <div class="guideline"><%= t('.guidelines.caption') %></div>
    </dd>

    <dt><%= f.label :description %></dt>
    <dd>
      <%=
        f.text_area(
            :description,
            id:        "#{model_name}_description",
            cols:      80,
            rows:      5,
            maxlength: PostImage::DESCRIPTION_LIMIT,
            class: 'auto-expand',
            data: {
                min_rows: 5,
                max_rows: 20
            }
        )
      %>
    </dd>

    <dt><%= f.label :source_name %></dt>
    <dd>
      <%=
        f.text_field(
            :source_name,
            id:        "#{model_name}_source_name",
            size:      nil,
            maxlength: PostImage::META_LIMIT
        )
      %>
      <div class="guideline"><%= t('.guidelines.source_name') %></div>
    </dd>

    <dt><%= f.label :source_link %></dt>
    <dd>
      <%=
        f.url_field(
            :source_link,
            id:          "#{model_name}_source_link",
            size:        nil,
            maxlength:   Post::META_LIMIT,
            placeholder: t('.placeholders.source_link')
        )
      %>
      <div class="guideline"><%= t('.guidelines.source_link') %></div>
    </dd>

    <%= render(partial: 'shared/forms/entity_flags', locals: { f: f }) %>
  </dl>

  <%= render 'shared/forms/state_container' %>

  <div class="buttons">
    <%= f.hidden_field :post_id if entity.id.nil? %>
    <%= f.button t(:save), type: :submit, class: 'button-save' %>
  </div>
<% end %>

app/views/post_images/edit.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
  <%= link_to(t('admin.posts.nav_item.text'), admin_posts_path) %>
  <%= admin_post_link(@entity.post) %>
  <%= link_to(t('admin.posts.images.nav_text'), images_admin_post_path(id: @entity.id)) %>
  <%= admin_post_image_link(@entity) %>
  <span><%= t('.nav_text') %></span>
<% end %>

<article>
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= return_icon(admin_post_image_path(id: @entity.id)) %></li>
    <li class="danger"><%= destroy_icon(@entity) %></li>
  </ul>

  <%= render partial: 'form', locals: { entity: @entity } %>
</article>

app/views/post_images/new.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
  <%= link_to(t('admin.posts.nav_item.text'), admin_posts_path) %>
  <%= admin_post_link(@entity.type) unless @entity.type.nil? %>
  <span><%= t('.heading') %></span>
<% end %>

<article>
  <h1><%= t('.title') %></h1>

  <% unless @entity.post.nil? %>
    <ul class="actions">
      <li><%= back_icon(admin_post_path(id: @entity.post_id)) %></li>
    </ul>
  <% end %>

  <%= render partial: 'form', locals: { entity: @entity } %>
</article>